!!com.example.app.properties.PropertiesData
appiumProperties:
  platformName: android
  deviceName: device
  udid: f54bca160403
  app: /Users/Destn/Downloads/app-debug_v.1.0.apk
  automationName: UIAutomator2
  newCommandTimeout: 120
  autoGrantPermissions: true
